import OpenAI from 'openai';
import { getSQL } from './db.js';
import { getRandomTemplate } from './designTemplates.js';

let _openai: OpenAI | null = null;

function getOpenAI() {
  if (_openai) return _openai;
  if (!process.env.OPENAI_API_KEY) {
    throw new Error('OPENAI_API_KEY is required');
  }
  _openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
  return _openai;
}

export async function processResume(resumeId: string, originalText: string, userId: string, userPlan: string) {
  try {
    const sql = getSQL();
    const openai = getOpenAI();

    // Run optimization and scoring in parallel (fast)
    // Design generation happens after in background to avoid timeout
    const [optimizationResult, scoreResult] = await Promise.all([
      openai.chat.completions.create({
        model: 'gpt-4o-mini',
        messages: [
          {
            role: 'system',
            content: 'You are an expert resume writer and career coach. Your task is to transform resumes into ATS-optimized, professional documents that highlight achievements and use strong action verbs. Always output valid JSON with an "improvedText" field containing the complete rewritten resume.'
          },
          {
            role: 'user',
            content: `Rewrite this resume to make it more professional and ATS-friendly. Follow these guidelines:

1. Use strong action verbs (Led, Managed, Achieved, Spearheaded, etc.)
2. Quantify achievements with numbers, percentages, or metrics
3. Remove weak language like "some", "most of the time", "still learning"
4. Make bullet points concise and impact-focused
5. Improve formatting and structure
6. Maintain all contact information and dates exactly as provided
7. Keep the same overall length and sections

Resume to improve:
${originalText.substring(0, 3000)}

Return ONLY valid JSON in this exact format:
{"improvedText": "the complete improved resume text here"}`,
          },
        ],
        response_format: { type: 'json_object' },
        max_tokens: 2500,
      }),
      openai.chat.completions.create({
        model: 'gpt-4o-mini',
        messages: [
          {
            role: 'system',
            content: 'You are an ATS (Applicant Tracking System) expert and resume evaluator. Analyze resumes and provide detailed scores and actionable feedback. Always output valid JSON.'
          },
          {
            role: 'user',
            content: `Analyze this resume and provide scores and specific issues:

Resume:
${originalText.substring(0, 1200)}

Evaluate:
1. ATS Score (0-100): How well would this pass automated screening systems?
   - Consider: keywords, formatting, structure, quantifiable achievements
2. Keywords Score (0-10): Presence of relevant industry keywords and action verbs
3. Formatting Score (0-10): Professional structure, consistency, readability
4. Issues: Specific problems to fix (weak verbs, missing metrics, formatting issues, etc.)

Return ONLY valid JSON in this exact format:
{
  "atsScore": 85,
  "keywordsScore": 7,
  "formattingScore": 8,
  "issues": [
    {"type": "weak-language", "message": "Replace 'some experience' with specific metrics", "severity": "high"},
    {"type": "missing-achievement", "message": "Add quantifiable results to work experience", "severity": "medium"}
  ]
}`,
          },
        ],
        response_format: { type: 'json_object' },
        max_tokens: 600,  // Reduced from 800
      }),
    ]);

    const optimization = JSON.parse(optimizationResult.choices[0].message.content || '{}');
    const scores = JSON.parse(scoreResult.choices[0].message.content || '{}');

    const improvedText = optimization.improvedText || originalText;

    // Update resume with text improvements and mark as completed
    // Design will be generated by separate API endpoint to avoid timeout
    await sql`
      UPDATE resumes SET
        improved_text = ${improvedText},
        ats_score = ${scores.atsScore || 70},
        keywords_score = ${scores.keywordsScore || 7},
        formatting_score = ${scores.formattingScore || 7},
        issues = ${JSON.stringify(scores.issues || [])},
        status = 'completed',
        updated_at = NOW()
      WHERE id = ${resumeId}
    `;

    console.log(`[Process] Resume ${resumeId} text optimization completed - design will be generated separately`);
  } catch (error) {
    console.error('[Process] Error optimizing resume:', error);
    const sql = getSQL();
    await sql`UPDATE resumes SET status = 'failed' WHERE id = ${resumeId}`;

    if (userPlan !== 'admin') {
      await sql`UPDATE users SET credits_remaining = credits_remaining + 1 WHERE id = ${userId}`;
      console.log(`[Credit] Refunded 1 credit to user ${userId} due to optimization failure`);
    }
  }
}

// Separate function for design generation (called by separate API endpoint)
export async function generateResumeDesign(resumeId: string) {
  try {
    const sql = getSQL();
    const openai = getOpenAI();

    // Get resume data
    const resumes = await sql`SELECT improved_text, original_text FROM resumes WHERE id = ${resumeId}`;
    if (resumes.length === 0) {
      throw new Error('Resume not found');
    }

    const resume = resumes[0];
    const improvedText = resume.improved_text || resume.original_text;

    // Get a random unique design template (now async!)
    const template = await getRandomTemplate();

    console.log(`[Design] Starting design generation for resume ${resumeId}`);

    const designResult = await openai.chat.completions.create({
      model: 'gpt-4o-mini',
      messages: [
        {
          role: 'system',
          content: `You are an award-winning resume designer from top design agencies (Pentagram, IDEO, Frog). Your resumes are featured in design galleries and win clients Fortune 500 interviews. Create PROFESSIONAL, POLISHED, EXECUTIVE-LEVEL resume designs that look like they cost $500 from a premium design studio. Use sophisticated typography, perfect spacing, elegant visual hierarchy, and refined color usage. Think: LinkedIn ProFinder top 1%, Canva Pro quality, Behance featured work. Always output valid JSON.`
        },
        {
          role: 'user',
          content: `Create a PROFESSIONAL, POLISHED resume design in HTML/CSS that looks EXPENSIVE and SOPHISTICATED - like it was designed by a top-tier design agency.

Resume content:
${improvedText}

TEMPLATE SPECIFICATION:
Name: ${template.name}
Style: ${template.style}
Layout Type: ${template.layout}
Gradient: ${template.gradient}
Accent: ${template.accentColor}
Fonts: ${template.fonts[0]} (headers), ${template.fonts[1]} (body)

🎨 PROFESSIONAL DESIGN REQUIREMENTS (CRITICAL - MAKE IT LOOK EXPENSIVE):

1. LAYOUT - ${template.layout.toUpperCase()} STRUCTURE:
${template.layout === '2-column' ? `   ✓ Grid: display: grid; grid-template-columns: 280px 1fr; height: 842px;
   ✓ SIDEBAR (280px): Gradient background ${template.gradient}, full height, elegant padding (30px)
   ✓ MAIN (remaining): Pure white (#ffffff), generous margins (40px), professional spacing
   ✓ Name at TOP of sidebar: Large (32px), bold (700), ${template.fonts[0]}, white, letter-spacing: 1px
   ✓ Job title below name: 13px, ${template.fonts[1]}, white, opacity: 0.95, elegant spacing
   ✓ NO photo - use elegant monogram circle instead: 80px circle with initials, subtle border` : ''}${template.layout === 'single-column' ? `   ✓ Container: max-width: 500px, centered, height: 842px
   ✓ Name: Large (36px), bold, ${template.fonts[0]}, color: ${template.accentColor}, centered, letter-spacing: 1px
   ✓ Job title: 16px, ${template.fonts[1]}, centered below name, margin: 8px 0
   ✓ Contact info: Horizontal row beneath title, 10px, separated by bullets (•)
   ✓ Sections: Full-width blocks with generous spacing (32px between), left-aligned content
   ✓ Headers: Centered or left-aligned, 16px, uppercase, ${template.accentColor}, underline or bottom border` : ''}${template.layout === 'timeline' ? `   ✓ Container: max-width: 550px, centered, height: 842px
   ✓ Header: Name (36px), title (14px), contact - all centered at top
   ✓ Timeline: Vertical line on left (3px solid ${template.accentColor}), connecting experience items
   ✓ Timeline dots: 16px circles on the line at each job, filled with ${template.accentColor}
   ✓ Experience cards: Offset from timeline (margin-left: 40px), with date badges
   ✓ Dates: Small badges (10px) positioned on timeline, background ${template.accentColor}, white text
   ✓ Visual flow: Connecting lines between timeline dots create career progression visualization` : ''}${template.layout === 'skills-first' ? `   ✓ Container: max-width: 595px, height: 842px
   ✓ Header: Name (34px) and title (14px) at top, ${template.accentColor}
   ✓ Skills Section: Immediately below header, prominent placement (top 25% of page)
   ✓ Skills Display: Grid of pills (3-4 columns), padding: 8px 16px, background: ${template.accentColor}15, border: 1px solid ${template.accentColor}50
   ✓ OR Skill bars: Horizontal bars showing proficiency, filled portion ${template.accentColor}
   ✓ Experience: Standard format below skills, condensed to fit remaining space
   ✓ Visual hierarchy: Skills visually dominant, larger and more colorful than experience` : ''}${template.layout === 'split-column' ? `   ✓ Grid: display: grid; grid-template-columns: 1fr 1fr; gap: 30px; height: 842px
   ✓ Header: Spans both columns, name (32px) and title (13px), ${template.accentColor}
   ✓ Left column: Experience (chronological work history)
   ✓ Right column: Skills, Education, Certifications
   ✓ Equal weight: Both columns same width (50/50), balanced visual importance
   ✓ Divider: Optional subtle vertical line between columns (1px, #e5e7eb)
   ✓ Symmetry: Matching spacing and alignment in both columns` : ''}${template.layout === 'header-banner' ? `   ✓ Banner: Full-width header (height: 180px), gradient ${template.gradient}, contains name and contact
   ✓ Name in banner: 36px, bold, white, ${template.fonts[0]}, centered or left-aligned with padding
   ✓ Title in banner: 14px, white, opacity 0.95, below name
   ✓ Contact in banner: Horizontal row, white icons/text, 11px
   ✓ Content below: 2-3 column grid (grid-template-columns: 1fr 2fr or three columns)
   ✓ Banner shadow: box-shadow: 0 4px 12px rgba(0,0,0,0.1) for depth
   ✓ Visual impact: Banner creates strong first impression, content organized beneath` : ''}

2. TYPOGRAPHY - EXECUTIVE-LEVEL REFINEMENT:
   ✓ Load Google Fonts: <link href="https://fonts.googleapis.com/css2?family=${template.fonts[0].replace(/ /g, '+')}:wght@300;400;600;700&family=${template.fonts[1].replace(/ /g, '+')}:wght@300;400;500;600&display=swap">
   ✓ Name: 32px, font-weight: 700, ${template.fonts[0]}, white, letter-spacing: 1px, line-height: 1.2
   ✓ Job Title: 13px, font-weight: 400, ${template.fonts[1]}, white, margin-top: 8px
   ✓ Section Headers (main): 14px, font-weight: 600, ${template.fonts[0]}, ${template.accentColor}, uppercase, letter-spacing: 2.5px, margin-bottom: 16px, border-bottom: 2px solid ${template.accentColor}, padding-bottom: 8px
   ✓ Body Text: 10px, font-weight: 400, ${template.fonts[1]}, #2c3e50, line-height: 1.6, perfect kerning
   ✓ Sidebar Headers: 11px, font-weight: 600, ${template.fonts[0]}, white, uppercase, letter-spacing: 1.5px, margin: 24px 0 12px
   ✓ Dates/Meta: 9px, font-weight: 500, #64748b, italic, spacing: 4px

3. COLOR PALETTE - REFINED & COHESIVE:
   ✓ Sidebar: ${template.gradient} (rich, saturated, professional)
   ✓ Main Headers: ${template.accentColor} (vibrant but sophisticated)
   ✓ Body Text: #2c3e50 (deep charcoal, not pure black - easier on eyes)
   ✓ Secondary Text: #64748b (elegant gray for dates/meta)
   ✓ Sidebar Text: #ffffff with subtle opacity variations (1.0 for name, 0.95 for details, 0.9 for labels)
   ✓ Skill Pills: background rgba(255,255,255,0.25), border: 1px solid rgba(255,255,255,0.3), padding: 6px 12px, border-radius: 20px

4. SPACING & WHITESPACE - BREATHING ROOM:
   ✓ Section Margins: 28px between sections (never cramped!)
   ✓ Sidebar Padding: 30px all sides (luxurious feel)
   ✓ Main Content Padding: 40px top, 45px right, 40px bottom, 40px left
   ✓ Paragraph Spacing: 12px between bullet points, 20px between jobs
   ✓ Line Height: Body 1.6, Headers 1.3 (perfect readability)
   ✓ Letter Spacing: Headers +2.5px, Name +1px (premium look)

5. VISUAL POLISH - DETAILS THAT MATTER:
   ✓ Subtle shadow on container: box-shadow: 0 4px 24px rgba(0,0,0,0.08);
   ✓ Elegant dividers in sidebar: border-top: 1px solid rgba(255,255,255,0.2), margin: 20px 0
   ✓ Skill tags: Use CSS pills with hover effect, rounded corners (20px), subtle shadows
   ✓ Job titles: font-weight: 600, font-size: 11px, color: #1e293b, margin-bottom: 4px
   ✓ Company names: font-weight: 500, font-size: 10px, color: ${template.accentColor}, margin-bottom: 6px
   ✓ Bullet points: Custom styled (▸ or elegant • with ${template.accentColor}), proper indentation (20px)
   ✓ Contact info: Icon-like symbols (📧 ☎ 📍 🌐) or elegant Unicode, spacing: 10px between items

6. PROFESSIONAL TOUCHES - WHAT SETS IT APART:
   ✓ Monogram circle: 80px circle at top of sidebar, white border (3px), background rgba(255,255,255,0.15), centered initials (24px, bold)
   ✓ Subtle texture: Add very subtle pattern/noise to sidebar for depth (optional: repeating-linear-gradient)
   ✓ Print-friendly: All measurements in px, @page { margin: 0; size: letter; }
   ✓ Modern bullet style: Use elegant shapes (▸ or custom SVG-like), colored with accent
   ✓ Hierarchy: Clear visual weight - Name > Section Headers > Job Titles > Body
   ✓ Consistency: All spacing follows 4px grid (4, 8, 12, 16, 20, 24, etc.)

7. SINGLE-PAGE CONSTRAINT (CRITICAL):
   ✓ Container: width: 595px, height: 842px (exact US Letter), overflow: hidden
   ✓ Font sizes: Precisely calculated - Name 32px, Headers 14px, Body 10px, Meta 9px
   ✓ Strategic spacing: Use all sizing values given above - they're calculated to fit perfectly
   ✓ If too long: Reduce bullet points to 2-3 per job, shorten summary, prioritize recent experience
   ✓ CSS: html, body { overflow: hidden !important; height: 842px !important; margin: 0; }

8. CODE STRUCTURE - CLEAN & SEMANTIC:
   ✓ DOCTYPE: <!DOCTYPE html>
   ✓ Full Google Fonts link with multiple weights
   ✓ ALL CSS in <style> tag (no external files)
   ✓ Semantic HTML5: <header>, <section>, <article>, <aside>
   ✓ Print CSS: @page { margin: 0; size: letter; } @media print { .container { box-shadow: none !important; } }

9. EXAMPLES OF PROFESSIONAL POLISH (Study these):
   ✓ Name Section: Monogram circle (80px) → Name (32px, bold, letter-spacing: 1px) → Title (13px, opacity: 0.95, margin-top: 8px) → Contact (10px icons, spacing: 10px)
   ✓ Experience Entry: Company (10px, ${template.accentColor}, bold) | Job Title (11px, #1e293b, semibold) | Dates (9px, italic, #64748b) → Bullets with custom ▸ markers
   ✓ Skills Section: Pill-style tags, each: padding: 6px 12px, border-radius: 20px, background: rgba(255,255,255,0.25), margin: 4px
   ✓ Section Header: Text (14px, uppercase, letter-spacing: 2.5px, ${template.accentColor}) + 2px bottom border + 16px margin-bottom

💎 FINAL QUALITY CHECK - DOES IT LOOK LIKE A $500 PREMIUM RESUME?
   ✓ Typography: Perfect hierarchy, elegant spacing, professional fonts
   ✓ Color: Cohesive palette, not garish, sophisticated gradients
   ✓ Whitespace: Generous but efficient, never cramped
   ✓ Details: Monogram, custom bullets, pill tags, elegant dividers
   ✓ Overall: Could this be on Behance? Would a Fortune 500 recruiter be impressed?

CRITICAL: You MUST return ONLY a single JSON object. Do NOT include any markdown, explanations, apologies, or extra text.
Start your response with { and end with }. Nothing else.

Expected JSON format:
{
  "html": "<!DOCTYPE html><html>...complete polished HTML...</html>",
  "templateName": "${template.name}",
  "style": "${template.style}",
  "colorScheme": "${template.accentColor}"
}`,
        },
      ],
      response_format: { type: 'json_object' },
      max_tokens: 4000,
    });

    console.log(`[Design] OpenAI design API call completed for resume ${resumeId}`);

    let design;
    try {
      const content = designResult.choices[0].message.content || '{}';
      design = JSON.parse(content);
    } catch (parseError) {
      console.error('[Design] JSON parse error:', parseError);
      console.error('[Design] Raw content:', designResult.choices[0].message.content?.substring(0, 500));
      throw new Error('AI generated invalid JSON format');
    }
    const designHtml = design.html;

    if (!designHtml) {
      throw new Error('No HTML generated');
    }

    // Update resume with design
    await sql`
      UPDATE resumes SET
        improved_html = ${designHtml},
        updated_at = NOW()
      WHERE id = ${resumeId}
    `;

    console.log(`[Design] Resume ${resumeId} updated with HTML design`);

    // Save template to database
    if (design.templateName) {
      try {
        // Make template name unique by appending resume ID (first 8 chars)
        const uniqueTemplateName = `${design.templateName} (${resumeId.substring(0, 8)})`;

        await sql`
          INSERT INTO resume_templates (
            name,
            style,
            color_scheme,
            html_template,
            preview_image_url,
            is_ai_generated,
            usage_count,
            created_from_resume_id
          ) VALUES (
            ${uniqueTemplateName},
            ${design.style || 'modern'},
            ${design.colorScheme || 'blue'},
            ${designHtml},
            ${null},
            ${true},
            ${0},
            ${resumeId}
          )
          ON CONFLICT (name) DO NOTHING
        `;
        console.log(`[Template] Successfully saved template: ${uniqueTemplateName}`);
      } catch (templateErr) {
        console.error(`[Template] Failed to save template:`, templateErr);
      }
    }

    return { success: true, html: designHtml };
  } catch (error) {
    console.error(`[Design] Error generating design for resume:`, error);
    throw error;
  }
}

export default processResume;
