import OpenAI from 'openai';
import { getSQL } from '../_shared';
import { getRandomTemplate } from './designTemplates';
import { validateResumeContrast } from './contrastValidator';

let _openai: OpenAI | null = null;

function getOpenAI() {
  if (_openai) return _openai;
  if (!process.env.OPENAI_API_KEY) {
    throw new Error('OPENAI_API_KEY is required');
  }
  _openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
  return _openai;
}

export async function processResume(resumeId: string, originalText: string, userId: string, userPlan: string) {
  try {
    const sql = getSQL();
    const openai = getOpenAI();

    // Run optimization and scoring in parallel (fast)
    // Design generation happens after in background to avoid timeout
    const [optimizationResult, scoreResult] = await Promise.all([
      openai.chat.completions.create({
        model: 'gpt-4o-mini',
        messages: [
          {
            role: 'system',
            content: 'You are an expert resume writer and career coach. Your task is to transform resumes into ATS-optimized, professional documents that highlight achievements and use strong action verbs. Always output valid JSON with an "improvedText" field containing the complete rewritten resume.'
          },
          {
            role: 'user',
            content: `Rewrite this resume to make it more professional and ATS-friendly. Follow these guidelines:

1. Use strong action verbs (Led, Managed, Achieved, Spearheaded, etc.)
2. Quantify achievements with numbers, percentages, or metrics
3. Remove weak language like "some", "most of the time", "still learning"
4. Make bullet points concise and impact-focused
5. Improve formatting and structure
6. Maintain all contact information and dates exactly as provided
7. Keep the same overall length and sections

Resume to improve:
${originalText.substring(0, 3000)}

Return ONLY valid JSON in this exact format:
{"improvedText": "the complete improved resume text here"}`,
          },
        ],
        response_format: { type: 'json_object' },
        max_tokens: 2500,
      }),
      openai.chat.completions.create({
        model: 'gpt-4o-mini',
        messages: [
          {
            role: 'system',
            content: 'You are an ATS (Applicant Tracking System) expert and resume evaluator. Analyze resumes and provide detailed scores and actionable feedback. Always output valid JSON.'
          },
          {
            role: 'user',
            content: `Analyze this resume and provide scores and specific issues:

Resume:
${originalText.substring(0, 1200)}

Evaluate:
1. ATS Score (0-100): How well would this pass automated screening systems?
   - Consider: keywords, formatting, structure, quantifiable achievements
2. Keywords Score (0-10): Presence of relevant industry keywords and action verbs
3. Formatting Score (0-10): Professional structure, consistency, readability
4. Issues: Specific problems to fix (weak verbs, missing metrics, formatting issues, etc.)

Return ONLY valid JSON in this exact format:
{
  "atsScore": 85,
  "keywordsScore": 7,
  "formattingScore": 8,
  "issues": [
    {"type": "weak-language", "message": "Replace 'some experience' with specific metrics", "severity": "high"},
    {"type": "missing-achievement", "message": "Add quantifiable results to work experience", "severity": "medium"}
  ]
}`,
          },
        ],
        response_format: { type: 'json_object' },
        max_tokens: 600,  // Reduced from 800
      }),
    ]);

    const optimization = JSON.parse(optimizationResult.choices[0].message.content || '{}');
    const scores = JSON.parse(scoreResult.choices[0].message.content || '{}');

    const improvedText = optimization.improvedText || originalText;

    // Update resume with text improvements and mark as completed
    // Design will be generated by separate API endpoint to avoid timeout
    await sql`
      UPDATE resumes SET
        improved_text = ${improvedText},
        ats_score = ${scores.atsScore || 70},
        keywords_score = ${scores.keywordsScore || 7},
        formatting_score = ${scores.formattingScore || 7},
        issues = ${JSON.stringify(scores.issues || [])},
        status = 'completed',
        updated_at = NOW()
      WHERE id = ${resumeId}
    `;

    console.log(`[Process] Resume ${resumeId} text optimization completed - design will be generated separately`);
  } catch (error) {
    console.error('[Process] Error optimizing resume:', error);
    const sql = getSQL();
    await sql`UPDATE resumes SET status = 'failed' WHERE id = ${resumeId}`;

    if (userPlan !== 'admin') {
      await sql`UPDATE users SET credits_remaining = credits_remaining + 1 WHERE id = ${userId}`;
      console.log(`[Credit] Refunded 1 credit to user ${userId} due to optimization failure`);
    }
  }
}

// Separate function for design generation (called by separate API endpoint)
export async function generateResumeDesign(resumeId: string) {
  try {
    const sql = getSQL();
    const openai = getOpenAI();

    // Get resume data
    const resumes = await sql`SELECT improved_text, original_text FROM resumes WHERE id = ${resumeId}`;
    if (resumes.length === 0) {
      throw new Error('Resume not found');
    }

    const resume = resumes[0];
    const improvedText = resume.improved_text || resume.original_text;

    // Get a random unique design template (now async!)
    const template = await getRandomTemplate();

    console.log(`[Design] Starting design generation for resume ${resumeId}`);

    const designResult = await openai.chat.completions.create({
      model: 'gpt-4o-mini',
      messages: [
        {
          role: 'system',
          content: `You are a minimalist resume designer creating expensive-looking resumes for 2025. Your designs are EXTREMELY MINIMAL, clean, and typographically disciplined. Key principles: (1) Maximum white space - nothing cramped, generous margins (0.5-1 inch), consistent vertical rhythm, (2) ONE professional font only (Lato, Calibri, or Georgia) at 10-11pt body, 11-12pt headers, 14-18pt name, (3) ONE subtle accent color for structure only (navy, deep green, or burgundy), (4) Perfect alignment and pixel-precise spacing consistency, (5) NO icons, NO photos, NO graphics, NO decorative elements, (6) Looks like a premium business document first, designed object second. Think: minimalist luxury, Swiss design, NOT Canva templates. Always output valid JSON.`
        },
        {
          role: 'user',
          content: `Create an EXTREMELY MINIMAL, CLEAN resume design in HTML/CSS that looks like an expensive 2025 business document - NOT a Canva template.

Resume content:
${improvedText}

TEMPLATE SPECIFICATION:
Name: ${template.name}
Style: ${template.style}
Layout Type: ${template.layout}
Gradient: ${template.gradient}
Accent: ${template.accentColor}
Fonts: ${template.fonts[0]} (headers), ${template.fonts[1]} (body)

🎨 MINIMALIST DESIGN REQUIREMENTS (CRITICAL - MAXIMUM WHITE SPACE, ZERO CLUTTER):

1. LAYOUT - ${template.layout.toUpperCase()} STRUCTURE:
${template.layout === '2-column' ? `   ✓ Grid: display: grid; grid-template-columns: 280px 1fr; height: 842px;
   ✓ SIDEBAR (280px): Gradient background ${template.gradient}, full height, elegant padding (30px)
   ✓ MAIN (remaining): Pure white (#ffffff), generous margins (40px), professional spacing
   ✓ Name at TOP of sidebar: Large (32px), bold (700), ${template.fonts[0]}, white, letter-spacing: 1px
   ✓ Job title below name: 13px, ${template.fonts[1]}, white, opacity: 0.95, elegant spacing
   ✓ NO photo - use elegant monogram circle instead: 80px circle with initials, subtle border` : ''}${template.layout === 'single-column' ? `   ✓ Container: max-width: 500px, centered, height: 842px
   ✓ Name: Large (36px), bold, ${template.fonts[0]}, color: ${template.accentColor}, centered, letter-spacing: 1px
   ✓ Job title: 16px, ${template.fonts[1]}, centered below name, margin: 8px 0
   ✓ Contact info: Horizontal row beneath title, 10px, separated by bullets (•)
   ✓ Sections: Full-width blocks with generous spacing (32px between), left-aligned content
   ✓ Headers: Centered or left-aligned, 16px, uppercase, ${template.accentColor}, underline or bottom border` : ''}${template.layout === 'timeline' ? `   ✓ Container: max-width: 550px, centered, height: 842px
   ✓ Header: Name (36px), title (14px), contact - all centered at top
   ✓ Timeline: Vertical line on left (3px solid ${template.accentColor}), connecting experience items
   ✓ Timeline dots: 16px circles on the line at each job, filled with ${template.accentColor}
   ✓ Experience cards: Offset from timeline (margin-left: 40px), with date badges
   ✓ Dates: Small badges (10px) positioned on timeline, background ${template.accentColor}, white text
   ✓ Visual flow: Connecting lines between timeline dots create career progression visualization` : ''}${template.layout === 'skills-first' ? `   ✓ Container: max-width: 595px, height: 842px
   ✓ Header: Name (34px) and title (14px) at top, ${template.accentColor}
   ✓ Skills Section: Immediately below header, prominent placement (top 25% of page)
   ✓ Skills Display: Grid of pills (3-4 columns), padding: 8px 16px, background: ${template.accentColor}15, border: 1px solid ${template.accentColor}50
   ✓ OR Skill bars: Horizontal bars showing proficiency, filled portion ${template.accentColor}
   ✓ Experience: Standard format below skills, condensed to fit remaining space
   ✓ Visual hierarchy: Skills visually dominant, larger and more colorful than experience` : ''}${template.layout === 'split-column' ? `   ✓ Grid: display: grid; grid-template-columns: 1fr 1fr; gap: 30px; height: 842px
   ✓ Header: Spans both columns, name (32px) and title (13px), ${template.accentColor}
   ✓ Left column: Experience (chronological work history)
   ✓ Right column: Skills, Education, Certifications
   ✓ Equal weight: Both columns same width (50/50), balanced visual importance
   ✓ Divider: Optional subtle vertical line between columns (1px, #e5e7eb)
   ✓ Symmetry: Matching spacing and alignment in both columns` : ''}${template.layout === 'header-banner' ? `   ✓ Banner: Full-width header (height: 180px), gradient ${template.gradient}, contains name and contact
   ✓ Name in banner: 36px, bold, white, ${template.fonts[0]}, centered or left-aligned with padding
   ✓ Title in banner: 14px, white, opacity 0.95, below name
   ✓ Contact in banner: Horizontal row, white icons/text, 11px
   ✓ Content below: 2-3 column grid (grid-template-columns: 1fr 2fr or three columns)
   ✓ Banner shadow: box-shadow: 0 4px 12px rgba(0,0,0,0.1) for depth
   ✓ Visual impact: Banner creates strong first impression, content organized beneath` : ''}

2. TYPOGRAPHY - MINIMAL & DISCIPLINED (USE ONE FONT ONLY):
   ✓ Load ONE Google Font: <link href="https://fonts.googleapis.com/css2?family=${template.fonts[0].replace(/ /g, '+')}:wght@400;600;700&display=swap">
   ✓ ALL text uses ${template.fonts[0]} - header AND body (consistency is key to minimalism)
   ✓ Name: 14-18pt (19-24px), font-weight: 700, ${template.fonts[0]}, black or white, letter-spacing: 0px (no excessive tracking)
   ✓ Job Title: 11-12pt (15-16px), font-weight: 400, ${template.fonts[0]}, margin-top: 4px
   ✓ Section Headers: 11-12pt (15-16px), font-weight: 600, ${template.fonts[0]}, ${template.accentColor} OR black, uppercase, letter-spacing: 0.5px MAX, margin-bottom: 12px, simple 1px underline
   ✓ Body Text: 10-11pt (13-15px), font-weight: 400, ${template.fonts[0]}, #1a1a1a (dark gray, good contrast), line-height: 1.5
   ✓ Dates/Meta: Same 10-11pt as body, font-weight: 400, #666666 (medium gray), NOT italic (too decorative)

3. COLOR PALETTE - EXTREMELY RESTRAINED (ONE ACCENT MAX):
   ✓ Background: Pure white (#ffffff) - no textures, no gradients in main area
   ✓ Primary Text: #1a1a1a (near black with good contrast)
   ✓ Secondary Text: #666666 (medium gray for dates/metadata only)
   ✓ Accent Color: ${template.accentColor} - use SPARINGLY for section headers or name only
   ✓ Sidebar (if used): ${template.gradient} OR solid ${template.accentColor} - keep text white with excellent contrast
   ✓ NO decorative colors, NO multiple accent colors, NO colorful skill badges
   ✓ Skill Display: Simple text list OR minimal pills with light gray background (#f5f5f5), black text

4. SPACING & WHITESPACE - MAXIMUM WHITE SPACE (CRITICAL):
   ✓ Page Margins: 0.5-1 inch (36-72px) on all sides - generous breathing room
   ✓ Section Spacing: 24-32px between major sections (NEVER cramped, NEVER crowded)
   ✓ Line Height: 1.5-1.6 for body text (excellent readability)
   ✓ Paragraph Spacing: 8-12px between bullet points, 16-20px between job entries
   ✓ Vertical Rhythm: Consistent spacing grid (8px, 12px, 16px, 24px, 32px)
   ✓ Letter Spacing: 0-0.5px MAX (no excessive tracking - looks amateur)
   ✓ White space is a FEATURE, not wasted space - embrace emptiness

5. MINIMAL DETAILS - NO DECORATION, ONLY STRUCTURE:
   ✓ NO shadows, NO gradients (except sidebar background if template requires)
   ✓ NO icons - text only (email, phone, location written out or simple symbols)
   ✓ NO emoji - absolutely forbidden (📧 ☎ etc. look unprofessional)
   ✓ Dividers: Simple 1px lines only, color #e5e5e5 (light gray), used sparingly
   ✓ Bullet Points: Standard • or – (hyphen), color #1a1a1a, NO custom shapes or colors
   ✓ Job Titles: font-weight: 600, same size as body text, color: #1a1a1a
   ✓ Company Names: font-weight: 600 OR 400, color: ${template.accentColor} OR #1a1a1a, margin-bottom: 4px
   ✓ Contact Info: Plain text separated by | or • separator, NO icons

6. WHAT MAKES IT EXPENSIVE - RESTRAINT & PRECISION:
   ✓ NO monogram circles - minimalism means removing decoration
   ✓ NO textures, NO patterns - flat design only
   ✓ Print-friendly: All measurements in px, @page { margin: 0; size: letter; }
   ✓ Perfect Alignment: Every element aligns to a strict grid
   ✓ Hierarchy through SIZE & WEIGHT only: Name (larger, bolder) > Section Headers (medium, semibold) > Body (regular weight)
   ✓ Pixel-precise consistency: All spacing follows 8px grid (8, 12, 16, 24, 32, etc.)
   ✓ Quality is in the ABSENCE of decoration, not the presence

7. SINGLE-PAGE CONSTRAINT (CRITICAL):
   ✓ Container: width: 595px, height: 842px (exact US Letter), overflow: hidden
   ✓ Font sizes: Precisely calculated - Name 32px, Headers 14px, Body 10px, Meta 9px
   ✓ Strategic spacing: Use all sizing values given above - they're calculated to fit perfectly
   ✓ If too long: Reduce bullet points to 2-3 per job, shorten summary, prioritize recent experience
   ✓ CSS: html, body { overflow: hidden !important; height: 842px !important; margin: 0; }

8. CODE STRUCTURE - CLEAN & SEMANTIC:
   ✓ DOCTYPE: <!DOCTYPE html>
   ✓ Full Google Fonts link with multiple weights
   ✓ ALL CSS in <style> tag (no external files)
   ✓ Semantic HTML5: <header>, <section>, <article>, <aside>
   ✓ Print CSS: @page { margin: 0; size: letter; } @media print { .container { box-shadow: none !important; } }

9. EXAMPLES OF MINIMAL STRUCTURE (Study these):
   ✓ Name Section: Name (18-24px, bold, letter-spacing: 0px) → Title (15px, regular, margin-top: 4px) → Contact (plain text: email | phone | location, 13px)
   ✓ Experience Entry: Company (13px, ${template.accentColor} OR #1a1a1a, semibold) | Job Title (13px, #1a1a1a, semibold) | Dates (13px, #666666, regular, right-aligned) → Standard • bullets
   ✓ Skills Section: Simple comma-separated list OR minimal boxes: padding: 4px 8px, background: #f5f5f5, border: none, font-size: 13px, color: #1a1a1a
   ✓ Section Header: Text (15px, uppercase OR sentence case, letter-spacing: 0px, ${template.accentColor} OR #1a1a1a) + 1px bottom border + 12px margin-bottom

💎 FINAL QUALITY CHECK - DOES IT LOOK LIKE AN EXPENSIVE 2025 MINIMAL RESUME?
   ✓ Typography: ONE font only, perfect hierarchy through size/weight, NO excessive letter-spacing
   ✓ Color: ONE accent color used sparingly, mostly black/gray text on white
   ✓ Whitespace: MAXIMUM white space, generous margins (0.5-1 inch), consistent vertical rhythm
   ✓ Zero Clutter: NO icons, NO photos, NO monograms, NO decorative elements, NO shadows
   ✓ Overall: Looks like a premium business document, NOT a Canva template. Clean, minimal, expensive.

CRITICAL: You MUST return ONLY a single JSON object. Do NOT include any markdown, explanations, apologies, or extra text.
Start your response with { and end with }. Nothing else.

Expected JSON format:
{
  "html": "<!DOCTYPE html><html>...complete polished HTML...</html>",
  "templateName": "${template.name}",
  "style": "${template.style}",
  "colorScheme": "${template.accentColor}"
}`,
        },
      ],
      response_format: { type: 'json_object' },
      max_tokens: 4000,
    });

    console.log(`[Design] OpenAI design API call completed for resume ${resumeId}`);

    let design;
    try {
      const content = designResult.choices[0].message.content || '{}';
      design = JSON.parse(content);
    } catch (parseError) {
      console.error('[Design] JSON parse error:', parseError);
      console.error('[Design] Raw content:', designResult.choices[0].message.content?.substring(0, 500));
      throw new Error('AI generated invalid JSON format');
    }
    const designHtml = design.html;

    if (!designHtml) {
      throw new Error('No HTML generated');
    }

    // Validate contrast ratios (WCAG AA compliance)
    console.log('[Design] Validating contrast ratios...');
    const contrastValidation = validateResumeContrast(designHtml);

    if (!contrastValidation.passed) {
      console.warn('[Design] Contrast validation failed:', contrastValidation.summary);
      const failedChecks = contrastValidation.results.filter(r => !r.meetsAA);
      failedChecks.forEach(check => {
        console.warn(`  - ${check.context}: ${check.contrastRatio.toFixed(2)}:1 (needs 4.5:1)`);
      });
      console.warn('[Design] Design has poor contrast but proceeding anyway');
    } else {
      console.log('[Design] ✓ Contrast validation passed!', contrastValidation.summary);
    }

    // Update resume with design
    await sql`
      UPDATE resumes SET
        improved_html = ${designHtml},
        updated_at = NOW()
      WHERE id = ${resumeId}
    `;

    console.log(`[Design] Resume ${resumeId} updated with HTML design`);

    // Save template to database
    if (design.templateName) {
      try {
        // Make template name unique by appending resume ID (first 8 chars)
        const uniqueTemplateName = `${design.templateName} (${resumeId.substring(0, 8)})`;

        await sql`
          INSERT INTO resume_templates (
            name,
            style,
            color_scheme,
            html_template,
            preview_image_url,
            is_ai_generated,
            usage_count,
            created_from_resume_id
          ) VALUES (
            ${uniqueTemplateName},
            ${design.style || 'modern'},
            ${design.colorScheme || 'blue'},
            ${designHtml},
            ${null},
            ${true},
            ${0},
            ${resumeId}
          )
          ON CONFLICT (name) DO NOTHING
        `;
        console.log(`[Template] Successfully saved template: ${uniqueTemplateName}`);
      } catch (templateErr) {
        console.error(`[Template] Failed to save template:`, templateErr);
      }
    }

    return { success: true, html: designHtml };
  } catch (error) {
    console.error(`[Design] Error generating design for resume:`, error);
    throw error;
  }
}

export default processResume;
