export const PRICING_TIERS = {
  free: {
    id: 'free',
    name: 'Free Forever',
    stripePriceId: null,
    amount: 0,
    interval: 'month',
    features: [
      '1 resume optimization per month',
      'Basic ATS score only',
      'Standard PDF export (with watermark)',
      'GPT-3.5 AI model',
      'Community support only',
      'Limited to 1 page resumes',
    ],
    limits: {
      creditsPerMonth: 1,
      maxResumeOptimizations: 1,
      maxCoverLetters: 0,
      atsReportAccess: false,
      pdfExportQuality: 'standard',
      customTemplatesAccess: false,
      prioritySupport: false,
      aiModelTier: 'gpt-3.5-turbo',
      removeWatermark: false,
      exportFormats: ['pdf'],
      teamSeats: 1,
    },
  },
  starter: {
    id: 'starter',
    name: 'Starter',
    stripePriceId: process.env.STRIPE_PRICE_STARTER_MONTHLY || null,
    amount: 1900,
    interval: 'month',
    features: [
      '5 resume optimizations per month',
      '3 cover letter generations',
      'Full ATS report with keyword analysis',
      'Premium PDF export (no watermark)',
      'GPT-4o-mini AI model',
      'Email support (48h response)',
      'Up to 3 page resumes',
      'Export as PDF or DOCX',
    ],
    limits: {
      creditsPerMonth: 5,
      maxResumeOptimizations: 5,
      maxCoverLetters: 3,
      atsReportAccess: true,
      pdfExportQuality: 'premium',
      customTemplatesAccess: false,
      prioritySupport: false,
      aiModelTier: 'gpt-4o-mini',
      removeWatermark: true,
      exportFormats: ['pdf', 'docx'],
      teamSeats: 1,
    },
  },
  professional: {
    id: 'professional',
    name: 'Professional',
    stripePriceId: process.env.STRIPE_PRICE_PRO_MONTHLY || null,
    amount: 4900,
    interval: 'month',
    mostPopular: true,
    features: [
      'Unlimited resume optimizations',
      'Unlimited cover letter generations',
      'Full ATS report + keyword optimization',
      'Premium PDF/DOCX/TXT export',
      'GPT-4o AI model (best quality)',
      'Priority email support (24h response)',
      'Custom resume templates',
      'LinkedIn profile optimization',
      'Interview prep Q&A generator',
      'Up to 5 page resumes',
    ],
    limits: {
      creditsPerMonth: 999,
      maxResumeOptimizations: 999,
      maxCoverLetters: 999,
      atsReportAccess: true,
      pdfExportQuality: 'premium',
      customTemplatesAccess: true,
      prioritySupport: true,
      aiModelTier: 'gpt-4o',
      removeWatermark: true,
      exportFormats: ['pdf', 'docx', 'txt'],
      teamSeats: 1,
    },
  },
  business: {
    id: 'business',
    name: 'Business',
    stripePriceId: process.env.STRIPE_PRICE_BUSINESS_MONTHLY || null,
    amount: 9900,
    interval: 'month',
    features: [
      'Everything in Professional',
      '5 team seats',
      'Team analytics dashboard',
      'Dedicated account manager',
      'Custom branding',
      'API access',
      'White-label option',
      'Phone support',
    ],
    limits: {
      creditsPerMonth: 9999,
      maxResumeOptimizations: 9999,
      maxCoverLetters: 9999,
      atsReportAccess: true,
      pdfExportQuality: 'premium',
      customTemplatesAccess: true,
      prioritySupport: true,
      aiModelTier: 'gpt-4o',
      removeWatermark: true,
      exportFormats: ['pdf', 'docx', 'txt'],
      teamSeats: 5,
    },
  },
} as const;

export const CREDIT_PACKAGES = {
  small: {
    name: '5 Credits',
    stripePriceId: process.env.STRIPE_PRICE_CREDITS_5,
    amount: 700,
    credits: 5,
  },
  medium: {
    name: '15 Credits',
    stripePriceId: process.env.STRIPE_PRICE_CREDITS_15,
    amount: 1900,
    credits: 15,
  },
  large: {
    name: '50 Credits',
    stripePriceId: process.env.STRIPE_PRICE_CREDITS_50,
    amount: 4900,
    credits: 50,
  },
} as const;

export const CREDIT_COSTS = {
  resume_optimization: 1,
  cover_letter_generation: 1,
  ats_detailed_report: 2,
  premium_template: 3,
  linkedin_optimization: 2,
} as const;
